// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
$(function () {
    function navTab(indexPath) {
        if (window.location.href.indexOf(indexPath) > 0) {
            return true;
        } else {
            return false;
        }
    }
    var currNav;
    if (navTab('dayin')) {
        currNav = 1; $(".currHover").eq(currNav).addClass("hover");
    } else if (navTab('jianzhi')) {
        currNav = 2; $(".currHover").eq(currNav).addClass("hover");
    } else if (navTab('chuangye')) {
        currNav = 3; $(".currHover").eq(currNav).addClass("hover");
    } else if (navTab('MD-wz')) {
        currNav = 4; $(".currHover").eq(currNav).addClass("hover");
    } else {
        currNav = 0; $(".currHover").eq(currNav).addClass("hover");
    }
    function navHover(curr) {
        var $navHover = $(".currHover").eq(curr);
        $navHover.parent().css("border-color", "transparent").siblings().children().removeClass("hover");
        $(".publicNavHover").stop(true, false).animate({ "left": $navHover.parent().position().left, "width": $navHover.parent().width() + 41 }, 100, function () { $navHover.addClass("hover").parent().css("border-color", "#e7e7e7") });
        $(".publicNavHoverM").css({ "width": $navHover.parent().width() + 33 });
    }
    navHover(currNav);
    $(".publicNav_nav").children("p").hover(function () {
        var curr = $(this).index();
        navHover(curr);
    }, function () {
        //	$(this).children().removeClass("hover").css("color","#404040");
    })
    $(".publicNav_nav").hover(function () { }, function () { navHover(currNav) });
});
//µ¼º½ÇÐ»»½áÊø

$(function () {
    var price = 0;
    $(".jian").click(function () {
        price = $("#num").val();
        if ($("#num").val() == 0) {
            return
        }
        else {
            price--;
        }
        $("#num").val(price);
    })
    $(".jia").click(function () {
        price = $("#num").val();
        price++;
        $("#num").val(price);
    })
})